services:
  postgres:
    image: postgres:15
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 30s
      retries: 3
    environment:
      - POSTGRES_PASSWORD=OldDaddyBlues
  back:
    build:
      dockerfile: ./dockerfile
      context: .
    ports:
      - 3000:3000
    restart: always

    depends_on:
      postgres:
        condition: service_started
    networks:
      - local

volumes:
  postgresdata:

networks:
  local:
    driver: bridge